### ISSUE TITLE
Simple test app using 2.0.0-dev.7 won't build

### ISSUE THREAD

**Issue by jordan0day** [scouten/sqlite_ecto2#174]
First off, thanks for creating an Ecto 2.* adapter for sqlite!

I'm on Elixir 1.4.2 on OS X, and I created a new project via the standard `mix new` route. I added :sqlite_ecto2 2.0.0-dev.7 as the sole dependency of the project, `mix deps.get && mix compile` fetches and builds all the dependencies *except* sqlite_ecto2:
```
== Compilation error on file lib/sqlite_db_connection/protocol.ex ==
** (CompileError) lib/sqlite_db_connection/protocol.ex:5: module DBConnection is not loaded and could not be found
    (elixir) expanding macro: Kernel.use/1
    lib/sqlite_db_connection/protocol.ex:5: Sqlite.DbConnection.Protocol (module)
    (elixir) lib/kernel/parallel_compiler.ex:117: anonymous fn/4 in Kernel.ParallelCompiler.spawn_compilers/1
```

I added db_connection as a dep in my mix.exs, re-fetched and everything built happily. `db_connection` is currently marked as an `optional` dependency in sqlite-ecto2 -- should it become a hard dependency?

**Comment by scouten** [comment]
@jordan0day thanks for pointing this out. I've changed it to a hard dependency in #175 and will be releasing a new version shortly.
