### ISSUE TITLE
mix deps.get error

### ISSUE THREAD

**Issue by muslih** [scouten/sqlite_ecto2#93]
Hi, thank you for your sqlite_ecto2 repo, i really appreciate it.

i get problems while run `mix deps.get` since a week ago, it always return
```elixir
Failed to fetch record for 'sqlite_ecto2' from registry (using cache)
<?xml version="1.0" encoding="UTF-8"?>
<Error><Code>AccessDenied</Code><Message>Access Denied</Message><RequestId>97EAB3D58FA1C6F7</RequestId><HostId>obypkz9umCOm6OH1Kb7YQAVIjTm+sKh/JQ1BTPRQTOHyuNBA9trf/eWer78SJnImUzwUQ2VuFpc=</HostId></Error>
** (Mix) No package with name sqlite_ecto2 (from: mix.exs) in registry
```

is there any solution? 
Thank you

**Comment by scouten** [comment]
Sorry I didn't see this earlier. IIRC I had to retract the 2.0.0-dev.0 release because of some error in the way I published it. Try now (using 2.0.0-dev.1).
